# student data
this notebook analyizes pass/fail data for a class

In [1]:
data = [50, 50, 47, 65, 72, 38, 81, 55, 49, 90, 44, 67, 73, 52, 35, 60, 48, 77, 58, 42, 85, 51, 46, 69, 33, 74, 62, 57, 40, 88]
print(data * 2)

[50, 50, 47, 65, 72, 38, 81, 55, 49, 90, 44, 67, 73, 52, 35, 60, 48, 77, 58, 42, 85, 51, 46, 69, 33, 74, 62, 57, 40, 88, 50, 50, 47, 65, 72, 38, 81, 55, 49, 90, 44, 67, 73, 52, 35, 60, 48, 77, 58, 42, 85, 51, 46, 69, 33, 74, 62, 57, 40, 88]

In [2]:
import numpy as np

grades = np.array(data)

print(grades * 2)

[100 100  94 130 144  76 162 110  98 180  88 134 146 104  70 120  96 154
 116  84 170 102  92 138  66 148 124 114  80 176]

In [3]:
grades.shape

(30,)

In [4]:
grades[7]

np.int64(55)

In [5]:
grades.mean()

np.float64(58.6)

In [6]:
study_hours = [5.0, 4.10, 3.07, 7.23, 8.45, 2.0, 9.12, 6.0, 4.0, 10.15, 3.45, 7.12, 8.23, 5.75, 2.0, 6.0, 4.0,
    9.0, 6.0, 3.15, 10.65, 5.0, 4.0, 7.0, 2.25, 8.45, 6.45, 5.55, 3.55, 9.0]

student_data = np.array([study_hours, grades])

In [7]:
student_data[1][0]

np.float64(50.0)

In [8]:
avg_study = student_data[0].mean()
avg_grade = student_data[1].mean()

print(f'Average Study Time: {avg_study}\nAverage Grade: {avg_grade}')

Average Study Time: 5.857333333333332
Average Grade: 58.6

In [9]:
import pandas as pd 

df_students = pd.DataFrame({'Name': ['John', 'Mary', 'Peter', 'David', 'Sarah', 'Michael', 'Grace', 'Daniel', 'Emily', 'James',
                                    'Sophia', 'William', 'Olivia', 'Benjamin', 'Chloe', 'Samuel', 'Jessica', 'Alexander', 'Emma', 'Matthew',
                                    'Ava', 'Joseph', 'Mia', 'Henry', 'Isabella', 'Noah', 'Amelia', 'Lucas', 'Charlotte', 'Ethan'],
                            'StudyHours':student_data[0],
                            'Grade':student_data[1]})

df_students

         Name  StudyHours  Grade
0        John        5.00   50.0
1        Mary        4.10   50.0
2       Peter        3.07   47.0
3       David        7.23   65.0
4       Sarah        8.45   72.0
5     Michael        2.00   38.0
6       Grace        9.12   81.0
7      Daniel        6.00   55.0
8       Emily        4.00   49.0
9       James       10.15   90.0
10     Sophia        3.45   44.0
11    William        7.12   67.0
12     Olivia        8.23   73.0
13   Benjamin        5.75   52.0
14      Chloe        2.00   35.0
15     Samuel        6.00   60.0
16    Jessica        4.00   48.0
17  Alexander        9.00   77.0
18       Emma        6.00   58.0
19    Matthew        3.15   42.0
20        Ava       10.65   85.0
21     Joseph        5.00   51.0
22        Mia        4.00   46.0
23      Henry        7.00   69.0
24   Isabella        2.25   33.0
25       Noah        8.45   74.0
26     Amelia        6.45   62.0
27      Lucas        5.55   57.0
28  Charlotte        3.55   40.0
29      Ethan        9.00   88.0

In [10]:
df_students.loc[10, 'Name']

'Sophia'

In [11]:
df_students.loc[df_students['Name']=='Sophia']

      Name  StudyHours  Grade
10  Sophia        3.45   44.0

In [12]:
df_students.query('Name=="Emma"')

    Name  StudyHours  Grade
18  Emma         6.0   58.0

In [13]:
url = "https://raw.githubusercontent.com/mahaveergautamji/Data-Project/main/data/student_dataset_v2.csv"

df_student = pd.read_csv(url, delimiter=',', header='infer')

In [14]:
df_student = pd.read_csv(url, delimiter=',', header='infer')

df_student = df_student[['Student_Name', 'Study_Hours', 'Marks']].head(22)

df_student

       Student_Name  Study_Hours  Marks
0       Mohit Gupta         10.8   97.0
1     Vivaan Kapoor          7.6   70.0
2       Aarush Shah         11.1   76.0
3       Dhruv Kumar          2.0  100.0
4   Siddharth Gupta          3.2    NaN
5      Karan Kapoor          1.5   48.0
6       Deepak Nair          4.6   59.0
7         Sai Reddy          5.3  -20.0
8        Riya Verma          4.0   29.0
9      Vivaan Singh         10.1   74.0
10      Pranav Shah          4.9   56.0
11      Shreya Iyer          4.1   66.0
12      Vivaan Nair          7.0   86.0
13   Advik Malhotra          2.6   97.0
14   Rahul Malhotra          9.8   62.0
15    Pooja Agarwal          1.8   79.0
16      Dhruv Mehta          NaN   21.0
17        Divya Rao          9.5   53.0
18       Dev Sharma          3.2   56.0
19     Mayank Joshi         26.0   71.0
20      Raj Agarwal         10.0   93.0
21         Pihu Rao          8.8   52.0

In [29]:
df_student.isnull().sum()

Student_Name    0
Study_Hours     0
Marks           0
dtype: int64

In [25]:
df_student.Study_Hours = df_student.Study_Hours.fillna(df_student.Study_Hours.mean())

In [ ]:
df_student = df_student.dropna(axis=0)

In [33]:
# Get the mean study hours using to column name as an index 
mean_study = df_student['Study_Hours'].mean()

# Get the mean marks using the column name as a property (just to make a point)
mean_marks = df_student.Marks.mean()

# print the mean study hours and mean marks 
print('Average weekly study hours: {:.2f}\nAverage marks: {: 2f}'.format(mean_study, mean_marks))

Average weekly study hours: 7.23
Average marks:  63.095238

In [35]:
df_student[df_student.Study_Hours > mean_study].Marks.mean()

np.float64(72.0)

In [36]:
import pandas as pd

passed = pd.Series(df_student.Marks >= 60)
df_student = pd.concat([df_student, passed.rename('Passed')], axis=1)