# DATA QUERY

This notebook involves extracting insight from student pass/fail in a class

In [8]:
data = (55, 45, 35, 65, 70, 80, 90, 60, 100, 50, 40, 30, 42, 48, 88, 92, 62, 10, 64, 78, 48, 65, 76, 87, 98, 85, 100)

print(data * 2)

(55, 45, 35, 65, 70, 80, 90, 60, 100, 50, 40, 30, 42, 48, 88, 92, 62, 10, 64, 78, 48, 65, 76, 87, 98, 85, 100, 55, 45, 35, 65, 70, 80, 90, 60, 100, 50, 40, 30, 42, 48, 88, 92, 62, 10, 64, 78, 48, 65, 76, 87, 98, 85, 100)

In [9]:
import numpy as np 

Marks = np.array(data)

print(Marks * 2)

[110  90  70 130 140 160 180 120 200 100  80  60  84  96 176 184 124  20
 128 156  96 130 152 174 196 170 200]

In [3]:
Marks.shape

(27,)

In [4]:
Marks.mean()

np.float64(65.29629629629629)

In [5]:
Marks[1]

np.int64(45)

In [7]:
Studyhours = [18, 15, 10, 22, 25, 28, 30, 20, 35, 16, 13, 9, 12, 14, 27, 21, 2, 17, 19, 12, 18, 20, 19, 21, 30, 32, 34]

Student_data = np.array([Marks, Studyhours])

In [13]:
Student_data[0][4]

np.int64(70)

In [14]:
avg_Marks = Student_data[0].mean()
avg_Studyhours = Student_data[1].mean()

print(f'Average Marks: {avg_Marks}\nAverage Study Time: {avg_Studyhours}')

Average Marks: 65.29629629629629
Average Study Time: 19.962962962962962

In [20]:
import pandas as pd 

df_student = pd.DataFrame ({'Name': ['James', 'John', 'Paul', 'Sam', 'Dan', 'Joy', 'Glory', 'Dammy', 'Sima', 'Jiggy', 'Mama', ' Son', 'Clara', 'Lad',
                                     'Jenny', 'Jude', 'Jesse', 'Lad', 'Mane', 'Omo', 'Labake', 'Oliver', 'Samuel', 'Dammy', 'Fav', 'Faith', 'Grace'],
                                     'Studyhours': Student_data[1],
                                     'Marks': Student_data[0]})

df_student

      Name  Studyhours  Marks
0    James          18     55
1     John          15     45
2     Paul          10     35
3      Sam          22     65
4      Dan          25     70
5      Joy          28     80
6    Glory          30     90
7    Dammy          20     60
8     Sima          35    100
9    Jiggy          16     50
10    Mama          13     40
11     Son           9     30
12   Clara          12     42
13     Lad          14     48
14   Jenny          27     88
15    Jude          21     92
16   Jesse           2     62
17     Lad          17     10
18    Mane          19     64
19     Omo          12     78
20  Labake          18     48
21  Oliver          20     65
22  Samuel          19     76
23   Dammy          21     87
24     Fav          30     98
25   Faith          32     85
26   Grace          34    100

In [21]:
df_student.isnull().sum()

Name          0
Studyhours    0
Marks         0
dtype: int64

In [22]:
df_student.query('Name=="Faith"')

     Name  Studyhours  Marks
25  Faith          32     85

In [ ]:
df_student.loc[df_student ['Name']== 'Omo']

   Name  Studyhours  Marks
19  Omo          12     78

In [25]:
df_student.loc[0, 'Name']

'James'